# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
language: cpp

sudo: false

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop
    - doc
    - ci

env:
  global:
    - secure: "UHit2f6Hq2pkHvx8rfrQvFacYiQKVO3vrCbNuDi/VSAIzQjRnqCqE06y4vpXLMsXf62TvBeCBStIuI8g+HP8B+f39oGb/9Om+yIgN/yes47R4sLFKFbRiOS6sfCIefJp7Kx7GSFf81xWxStpIU4QaSsk8Dlt5xyurTWXFSde+lQ="

  matrix:
    - BOGUS_JOB=true

matrix:
  exclude:
    - env: BOGUS_JOB=true
  include:
    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++11 VARIANT=debug
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++11 VARIANT=release
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++11 VARIANT=debug
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++11 VARIANT=release
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=c++11 VARIANT=debug
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=c++11 VARIANT=release
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=c++11 VARIANT=debug
      addons:
        apt:
          packages:
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=c++11 VARIANT=release
      addons:
        apt:
          packages:
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11 VARIANT=debug

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11 VARIANT=release

    - env: DOC=1
      addons:
        apt:
          packages:
            - doxygen

install:
  - |-
    if [ "$DOC" ]; then
      pip install --user sphinx
    fi
  - cd ..
  - git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/gil
  - cp -r $TRAVIS_BUILD_DIR/.ci libs/gil
  - python tools/boostdep/depinst/depinst.py gil
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    if [ "$DOC" ]; then
      echo "using doxygen ;" > ~/user-config.jam
      ./b2 libs/gil/doc
    else
      echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
      ./b2 libs/gil/test toolset=$TOOLSET variant=$VARIANT
      ./b2 libs/gil/toolbox/test toolset=$TOOLSET variant=$VARIANT
      ./b2 libs/gil/numeric/test toolset=$TOOLSET variant=$VARIANT
      ./b2 libs/gil/io/test//simple toolset=$TOOLSET variant=$VARIANT
    fi

after_success:
# Upload docs only when building upstream.
- |
   if [ "$DOC" -a \
        "$TRAVIS_REPO_SLUG" = "boostorg/gil" -a \
        "$TRAVIS_PULL_REQUEST" = "false" ]; then
     export GH_TOKEN
     cd libs/gil
     .ci/upload_docs.sh
   fi


notifications:
  email:
    on_success: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f59b626f2ed08f3d30ab
    # options: [always|never|change]
    on_success: change # default: always
    on_failure: always # default: always
    on_start:   change # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always
